requires 'Config::Identity';
requires 'Encode';
requires 'List::Util';
requires 'List::UtilsBy';
requires 'Text::Xslate';
requires 'Time::Moment';
requires 'WWW::Connpass', '0.02';
requires 'YAML::Tiny';
requires 'parent';
requires 'perl', '5.14';
