---
event:
  id: 10
  url: ~
  thema:
    title: TBD
    description: |-
      TBD
  venue:
    name: 株式会社ガイアックス
    address: 東京都品川区西五反田1-21-8 (KSS五反田ビル 6F)
    url: http://www.gaiax.co.jp/corporate/access/
    capacity: 40
  date: 2016-09-30
  open_at: 19:00
  start_at: 19:30
  timetable:
    - type: announce
      minutes: 10
    - type: talk
      minutes: 20
      speaker: undef
      detail: undef
    - type: talk
      minutes: 20
      speaker: undef
      detail: undef
    - type: break
      minutes: 10
    - type: lt
      minutes: 5
      speaker: undef
      detail: undef
    - type: lt
      minutes: 5
      speaker: undef
      detail: undef
    - type: lt
      minutes: 5
      speaker: TomooAmano
      detail: Amon2 で書かれた API サーバ開発を引き継いだ話
    - type: lt
      minutes: 5
      speaker: papix
      detail: Okinawa.pm行ってきた(仮)
    - type: lt
      minutes: 5
      speaker: okazu_dm
      detail: Google Cloud Platformで動くPerl
    - type: lt
      minutes: 5
      speaker: undef
      detail: undef
    - type: party
      minutes: 120
  sponsors: []
    # - name: ~
    #   url: ~
  party:
    venue: TBD
    fee: 2500
