---
event:
  id: 9
  url: http://gotanda-pm.connpass.com/event/33757/
  thema:
    title: Plack
    description: |-
      Plackを使っていないWebアプリはないんじゃないか？と思えるほどPlackは普及しているかと思います。  
      その上で運用上のtipsなども溜まってきているのではないでしょうか。そういうものを是非紹介していただければと思います。  
      また、Plackも少しづつ進化しています。Plackの最新情報も共有していきましょう。  
  venue:
    name: 株式会社モバイルファクトリー
    address: 東京都品川区東五反田1-24-2 (東五反田1丁目ビル8階)
    url: http://www.mobilefactory.jp/corporate/access
    capacity: 40
  date: 2016-06-29
  open_at: 19:00
  start_at: 19:30
  timetable:
    - type: announce
      minutes: 10
    - type: talk
      minutes: 20
      speaker: skaji
      detail: Reactive Programming in Perl6
    - type: talk
      minutes: 20
      speaker: undef
      detail: undef
    - type: break
      minutes: 10
    - type: lt
      minutes: 5
      speaker: karupanerura
      detail: Motherでバブみのあるイベント運営
    - type: lt
      minutes: 5
      speaker: bayashi
      detail: Perlおじさんの愉快な開発
    - type: lt
      minutes: 5
      speaker: TomooAmano
      detail: Amon2 で書かれた API サーバ開発を引き継いだ話
    - type: lt
      minutes: 5
      speaker: papix
      detail: Okinawa.pm行ってきた(仮)
    - type: lt
      minutes: 5
      speaker: okazu_dm
      detail: Google Cloud Platformで動くPerl
    - type: lt
      minutes: 5
      speaker: undef
      detail: undef
    - type: party
      minutes: 120
  sponsors: []
    # - name: ~
    #   url: ~
  party:
    venue: ぼたん
    fee: 2500
