---
event:
  id: 18
  url: https://gotanda-pm.connpass.com/event/89459/
  thema:
    title: UNIXとPerl
    description: |-
      今回の Gotanda.pm は、ゲストに kazeburo さんをお招きして、UNIX と Perl というテーマで開催です!
      
  venue:
    name: 株式会社メルカリ
    address: 東京都港区六本木6-10-1（六本木ヒルズ森タワー18F）
    url: https://about.mercari.com/about/#locations
    capacity: 30
  date: 2018-06-15
  open_at: 19:00
  start_at: 19:30
  timetable:
    - type: announce
      minutes: 5 
    - type: talk
      minutes: 30
      speaker: kazeburo
      detail: UNIXとPerl
    - type: lt
      minutes: 5
      speaker: undef
      detail: undef
    - type: lt
      minutes: 5
      speaker: undef
      detail: undef
    - type: lt
      minutes: 5
      speaker: undef
      detail: undef
    - type: lt
      minutes: 5
      speaker: undef
      detail: undef
    - type: lt
      minutes: 5
      speaker: undef
      detail: undef
    - type: lt
      minutes: 5
      speaker: undef
      detail: undef
    - type: lt
      minutes: 5
      speaker: undef
      detail: undef
    - type: lt
      minutes: 5
      speaker: undef
      detail: undef
    - type: party
      minutes: 90
  sponsors: []
    # - name: ~
    #   url: ~
  party:
    venue: undef
    fee: 5000
