---
event:
  id: 12
  url: https://gotanda-pm.connpass.com/event/52867/
  thema:
    title: Yet Another
    description: |-
      これまでに(あったり)なかったりしたアレコレについて話しましょう。
  venue:
    name: 株式会社モバイルファクトリー
    address: 東京都品川区東五反田1-24-2 (東五反田1丁目ビル8階)
    url: http://www.mobilefactory.jp/corporate/access
    capacity: 30
  date: 2017-03-29
  open_at: 19:00
  start_at: 19:30
  timetable:
    - type: announce
      minutes: 10
    - type: talk
      minutes: 20
      speaker: myfinder
      detail: YAPC - Yet Another Perl CGI
    - type: talk
      minutes: 20
      speaker: skaji
      detail: Make your CPAN module static installable
    - type: break
      minutes: 10
    - type: lt
      minutes: 5
      speaker: dokechin
      detail: 誰でもDWHを実現したいのだ！！グラフ描写用APIの仕様と実装
    - type: lt
      minutes: 5
      speaker: undef
      detail: undef
    - type: lt
      minutes: 5
      speaker: undef
      detail: undef
    - type: lt
      minutes: 5
      speaker: undef
      detail: undef
    - type: lt
      minutes: 5
      speaker: undef
      detail: undef
    - type: lt
      minutes: 5
      speaker: undef
      detail: undef
    - type: party
      minutes: 120
  sponsors: []
    # - name: ~
    #   url: ~
  party:
    venue: ぼたん
    fee: 2500
