---
event:
  id: 16
  url: ~
  thema: ~
    # title: undef
    # description: |-
  venue:
    name: 株式会社モバイルファクトリー
    address: 東京都品川区東五反田1-24-2 (東五反田1丁目ビル8階)
    url: http://www.mobilefactory.jp/corporate/access
    capacity: 30
  date: 2018-03-30
  open_at: 19:00
  start_at: 19:30
  timetable:
    - type: announce
      minutes: 10
    - type: talk
      minutes: 20
      speaker: undef
      detail: undef
    - type: talk
      minutes: 20
      speaker: undef
      detail: undef
    - type: break
      minutes: 10
    - type: lt
      minutes: 5
      speaker: undef
      detail: undef
    - type: lt
      minutes: 5
      speaker: undef
      detail: undef
    - type: lt
      minutes: 5
      speaker: undef
      detail: undef
    - type: lt
      minutes: 5
      speaker: undef
      detail: undef
    - type: party
      minutes: 120
  sponsors: []
    # - name: ~
    #   url: ~
  party:
    venue: 適当な店
    fee: 4000~5000
