---
event:
  id: 17
  url: https://gotanda-pm.connpass.com/event/84014/
  thema:
    title: Perl Getting Started
    description: |-
      春なので、ビギナー向けのPerl の話をしましょう!
  venue:
    name: freee株式会社
    address: 東京都品川区西五反田2-8-1 五反田ファーストビル 9F
    url: https://corp.freee.co.jp/company/
    capacity: 30
  date: 2018-04-16
  open_at: 19:00
  start_at: 19:30
  timetable:
    - type: announce
      minutes: 10
    - type: talk
      minutes: 20
      speaker: undef
      detail: undef
    - type: talk
      minutes: 20
      speaker: undef
      detail: undef
    - type: lt
      minutes: 5
      speaker: odan
      detail: rng-apiをAWS Lambdaに移行した時の話
    - type: lt
      minutes: 5
      speaker: _ybrliiu
      detail: ぼくがPerlで開発を行うときに工夫していること(仮)
    - type: lt
      minutes: 5
      speaker: MacoTasu
      detail: PerlからRubyに移って早3年。変数の定義の仕方すら忘れてしまったのでPerlを忘れない・思い出すためのお助けツールを作ってみた
    - type: lt
      minutes: 5
      speaker: tenmihi
      detail: jsで何か話します
    - type: party
      minutes: 90
  sponsors: []
    # - name: ~
    #   url: ~
  party:
    venue: freee 株式会社
    fee: 1000
