---
event:
  id: 16
  url: https://gotanda-pm.connpass.com/event/82791/
  thema: ~
    # title: undef
    # description: |-
  venue:
    name: 株式会社モバイルファクトリー
    address: 東京都品川区東五反田1-24-2 (東五反田1丁目ビル8階)
    url: http://www.mobilefactory.jp/corporate/access
    capacity: 30
  date: 2018-03-30
  open_at: 19:00
  start_at: 19:30
  timetable:
    - type: announce
      minutes: 10
    - type: lt
      minutes: 5
      speaker: karupanerura
      detail: Perl小ネタ
    - type: lt
      minutes: 5
      speaker: kfly8
      detail: Gotanda.pm 引き継ぎ式（？） / できたらなーと思っていること
    - type: lt
      minutes: 5
      speaker: Shouhei Yoshida
      detail: Firebaseで遊ぼう
    - type: lt
      minutes: 5
      speaker: mackee_w
      detail: postfix dereference 徹底攻略
    - type: lt
      minutes: 5
      speaker: papix
      detail: Smart::Args入門(仮)
    - type: lt
      minutes: 5
      speaker: Code-Hex
      detail: XS で作るクロージャ
    - type: lt
      minutes: 5
      speaker: undef
      detail: undef
    - type: lt
      minutes: 5
      speaker: undef
      detail: undef
    - type: party
      minutes: 120
  sponsors: []
    # - name: ~
    #   url: ~
  party:
    venue: 適当な店
    fee: 4000~5000
